## Tensors
- Tensors in PyTorch are similar to the ndarrays from NumPy, however tensors run on GPUs and other hardware accelerators.
- Tensors are highly optimised for Automatic Differentiation.

In [1]:
import torch
import numpy as np

In [8]:
# From Python List
data = [[1, 2], [3, 4]]
tensor = torch.tensor(data)
print("From Python List\n", tensor, end="\n")

# From NumPy Array
array = np.arange(1, 11).reshape(2, 5)
tensor = torch.from_numpy(array)
print("From ndarray\n", tensor, end="\n")

# From another Tensor by Structure
tensor_ones = torch.ones_like(tensor)
print("Same as Tensor with Ones\n", tensor_ones, end="\n")

# From another Tensor by Value and Structure
tensor_rand = torch.rand_like(tensor, dtype=torch.float)
print("Same as Tensor with new values\n", tensor_rand, end="\n")

tensor_randn = torch.randn_like(tensor, dtype=torch.float)
print("Same as Tensor with new values from normal distribution\n", tensor_randn, end="\n")

From Python List
 tensor([[1, 2],
        [3, 4]])
From ndarray
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Same as Tensor with Ones
 tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
Same as Tensor with new values
 tensor([[0.3110, 0.9610, 0.2283, 0.4134, 0.9879],
        [0.5834, 0.4659, 0.1277, 0.8026, 0.3287]])
Same as Tensor with new values from normal distribution
 tensor([[ 0.7459, -0.4413, -0.0657,  0.3865, -1.1455],
        [-0.3506,  0.8501, -0.4497, -0.9375, -1.1116]])


In [10]:
# Randomly Generated Tensors
shape = (3, 2, 4)

rand_tensor = torch.rand(shape)
print("Random Tensor from Uniform Distribution\n", rand_tensor, end="\n")

randn_tensor = torch.randn(shape)
print("Random Tensor from Normal Distribution\n", randn_tensor, end="\n")

zero_tensor = torch.zeros(shape)
print("Random Tensor of Zeros\n", zero_tensor, end="\n")

ones_tensor = torch.ones(shape)
print("Random Tensor of Ones\n", ones_tensor, end="\n")

Random Tensor from Uniform Distribution
 tensor([[[0.5464, 0.9183, 0.8916, 0.8160],
         [0.2907, 0.1234, 0.5945, 0.3335]],

        [[0.7520, 0.0723, 0.7129, 0.2175],
         [0.9247, 0.1487, 0.1825, 0.8493]],

        [[0.5231, 0.3300, 0.6922, 0.6443],
         [0.6239, 0.9048, 0.9479, 0.4333]]])
Random Tensor from Normal Distribution
 tensor([[[ 0.1355,  0.3161, -1.5148, -1.7348],
         [ 0.3769,  1.2826,  0.9275, -0.0081]],

        [[-1.2436,  1.8709,  0.2355,  0.4512],
         [-1.4771, -0.8445, -1.2022,  0.4216]],

        [[ 0.8909,  1.5391, -0.7561, -1.8856],
         [-1.6038,  1.3051, -0.6606,  0.5111]]])
Random Tensor of Zeros
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Random Tensor of Ones
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1.,

## Attributes of a Tensor
- PyTorch tensors have several accessible attributes
    - No of Dimensions
    - Shape
    - Datatype
    - Device

In [21]:
rand_tensor.ndim

3

In [11]:
rand_tensor.shape

torch.Size([3, 2, 4])

In [13]:
rand_tensor.dtype

torch.float32

In [14]:
rand_tensor.device

device(type='cpu')

**Important**
- By default all the Tensors created using PyTorch are stored on CPU.
- To utilise accelerators to allocate, store and operate on Tensors we need to utilise the `.to()`.
- However, it is evident that transferring large tensors between devices is expensive in terms of Time and Memory.

In [15]:
# Checking the availability of an Accelerator
if torch.accelerator.is_available():
    print("Device Found: ", torch.accelerator.current_accelerator().type)  # type: ignore
    print("Moving the tensor to the Device")
    randn_tensor = randn_tensor.to(torch.accelerator.current_accelerator())
    print(randn_tensor)
    print(randn_tensor.device)

Device Found:  mps
Moving the tensor to the Device
tensor([[[ 0.1355,  0.3161, -1.5148, -1.7348],
         [ 0.3769,  1.2826,  0.9275, -0.0081]],

        [[-1.2436,  1.8709,  0.2355,  0.4512],
         [-1.4771, -0.8445, -1.2022,  0.4216]],

        [[ 0.8909,  1.5391, -0.7561, -1.8856],
         [-1.6038,  1.3051, -0.6606,  0.5111]]], device='mps:0')
mps:0


## Indexing and Slicing

A simplified anatomy of Tensors, Matrices and Vectors

[source](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.avni.sh%2Fposts%2Fmath%2Flinear-algebra%2Ftensors%2F&psig=AOvVaw0VGDSt1kWNc9uPec2Bt0Zi&ust=1755448210343000&source=images&cd=vfe&opi=89978449&ved=0CBkQjhxqFwoTCPCVza3gj48DFQAAAAAdAAAAABAT)

![Anatomy of Tensors](./assets/tensors-anatomy.png)

In [16]:
rand = torch.rand((2, 3, 4))
print(rand)

tensor([[[0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740]],

        [[0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838]]])


In [17]:
print("First Row")
print(rand[0])

First Row
tensor([[0.2942, 0.1776, 0.4684, 0.2800],
        [0.9134, 0.3048, 0.1982, 0.1514],
        [0.6542, 0.0890, 0.0447, 0.0740]])


In [18]:
print("First Column")
print(rand[:, 0])

First Column
tensor([[0.2942, 0.1776, 0.4684, 0.2800],
        [0.8388, 0.4354, 0.0633, 0.7614]])


In [ ]:
print("Last Column 2D")
print(rand[:, -1])

Last Column
tensor([[0.6542, 0.0890, 0.0447, 0.0740],
        [0.4865, 0.0206, 0.7748, 0.2838]])


In [20]:
print("Last Column nD")
print(rand[..., -1])

Last Column nD
tensor([[0.2800, 0.1514, 0.0740],
        [0.7614, 0.7804, 0.2838]])


## Operations on Tensors

In [22]:
rand

tensor([[[0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740]],

        [[0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838]]])

In [23]:
# Concatenating against the first - 0th dimension
torch.cat([rand, rand], dim=0)

tensor([[[0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740]],

        [[0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838]],

        [[0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740]],

        [[0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838]]])

In [ ]:
# Concatenating against the second - 1st dimension
torch.cat([rand, rand], dim=1)

tensor([[[0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740],
         [0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740]],

        [[0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838],
         [0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838]]])

In [25]:
# Concatenating against the third - 2nd dimension
torch.cat([rand, rand], dim=2)

tensor([[[0.2942, 0.1776, 0.4684, 0.2800, 0.2942, 0.1776, 0.4684, 0.2800],
         [0.9134, 0.3048, 0.1982, 0.1514, 0.9134, 0.3048, 0.1982, 0.1514],
         [0.6542, 0.0890, 0.0447, 0.0740, 0.6542, 0.0890, 0.0447, 0.0740]],

        [[0.8388, 0.4354, 0.0633, 0.7614, 0.8388, 0.4354, 0.0633, 0.7614],
         [0.2949, 0.9845, 0.3496, 0.7804, 0.2949, 0.9845, 0.3496, 0.7804],
         [0.4865, 0.0206, 0.7748, 0.2838, 0.4865, 0.0206, 0.7748, 0.2838]]])

In [26]:
# Stacking on the 0th dimension
torch.stack([rand, rand], dim=0)

tensor([[[[0.2942, 0.1776, 0.4684, 0.2800],
          [0.9134, 0.3048, 0.1982, 0.1514],
          [0.6542, 0.0890, 0.0447, 0.0740]],

         [[0.8388, 0.4354, 0.0633, 0.7614],
          [0.2949, 0.9845, 0.3496, 0.7804],
          [0.4865, 0.0206, 0.7748, 0.2838]]],


        [[[0.2942, 0.1776, 0.4684, 0.2800],
          [0.9134, 0.3048, 0.1982, 0.1514],
          [0.6542, 0.0890, 0.0447, 0.0740]],

         [[0.8388, 0.4354, 0.0633, 0.7614],
          [0.2949, 0.9845, 0.3496, 0.7804],
          [0.4865, 0.0206, 0.7748, 0.2838]]]])

In [27]:
# Stacking on the 1st dimension
torch.stack([rand, rand], dim=1)

tensor([[[[0.2942, 0.1776, 0.4684, 0.2800],
          [0.9134, 0.3048, 0.1982, 0.1514],
          [0.6542, 0.0890, 0.0447, 0.0740]],

         [[0.2942, 0.1776, 0.4684, 0.2800],
          [0.9134, 0.3048, 0.1982, 0.1514],
          [0.6542, 0.0890, 0.0447, 0.0740]]],


        [[[0.8388, 0.4354, 0.0633, 0.7614],
          [0.2949, 0.9845, 0.3496, 0.7804],
          [0.4865, 0.0206, 0.7748, 0.2838]],

         [[0.8388, 0.4354, 0.0633, 0.7614],
          [0.2949, 0.9845, 0.3496, 0.7804],
          [0.4865, 0.0206, 0.7748, 0.2838]]]])

In [28]:
# Stacking on the 2nd dimension
torch.stack([rand, rand], dim=2)

tensor([[[[0.2942, 0.1776, 0.4684, 0.2800],
          [0.2942, 0.1776, 0.4684, 0.2800]],

         [[0.9134, 0.3048, 0.1982, 0.1514],
          [0.9134, 0.3048, 0.1982, 0.1514]],

         [[0.6542, 0.0890, 0.0447, 0.0740],
          [0.6542, 0.0890, 0.0447, 0.0740]]],


        [[[0.8388, 0.4354, 0.0633, 0.7614],
          [0.8388, 0.4354, 0.0633, 0.7614]],

         [[0.2949, 0.9845, 0.3496, 0.7804],
          [0.2949, 0.9845, 0.3496, 0.7804]],

         [[0.4865, 0.0206, 0.7748, 0.2838],
          [0.4865, 0.0206, 0.7748, 0.2838]]]])

In [31]:
# Matrix Multiplication
X = torch.rand(3, 2)
print("X:\n", X)

mul = X @ X.T
print("Matrix Mul:\n", mul)

mul = X.matmul(X.T)
print("Matrix Mul:\n", mul)

mul_final: torch.Tensor = torch.Tensor()
torch.matmul(X, X.T, out=mul_final)
print("Final Matrix Mul:\n", mul_final)

X:
 tensor([[0.9055, 0.5308],
        [0.6801, 0.1071],
        [0.7564, 0.2610]])
Matrix Mul:
 tensor([[1.1017, 0.6726, 0.8235],
        [0.6726, 0.4740, 0.5424],
        [0.8235, 0.5424, 0.6403]])
Matrix Mul:
 tensor([[1.1017, 0.6726, 0.8235],
        [0.6726, 0.4740, 0.5424],
        [0.8235, 0.5424, 0.6403]])
Final Matrix Mul:
 tensor([[1.1017, 0.6726, 0.8235],
        [0.6726, 0.4740, 0.5424],
        [0.8235, 0.5424, 0.6403]])


In [32]:
# Aggregations as Python Items
sum_val = X.sum()
print(sum_val)
print(sum_val.item())

tensor(3.2409)
3.2408676147460938
